# Generated by Django 2.2 on 2019-03-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemField', models.CharField(max_length=100)),
                ('imageUpload2', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WikiModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('textField', models.TextField(max_length=1000)),
                ('dateCreated', models.DateField(default='')),
                ('imageUpload', models.CharField(max_length=200)),
            ],
        ),
    ]
