# Generated by Django 2.2 on 2019-03-12 17:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wikiApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=200)),
                ('password1', models.CharField(default='', max_length=200)),
                ('password2', models.CharField(default='', max_length=200)),
                ('dateAccountCreated', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='wikimodel',
            name='dateCreated',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
