# Generated by Django 2.2 on 2019-03-12 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wikiApp', '0003_auto_20190312_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='foreignkeyToWiki',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wikiApp.WikiModel'),
        ),
        migrations.AlterField(
            model_name='wikimodel',
            name='foreignkeyToUserModel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wikiApp.UserModel'),
        ),
    ]
