# Generated by Django 2.2 on 2019-03-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikiApp', '0005_auto_20190314_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikimodel',
            name='imageUpload',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
    ]
