# Generated by Django 2.2 on 2019-03-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikiApp', '0006_auto_20190314_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikimodel',
            name='imageUpload',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
