# Generated by Django 2.2 on 2019-03-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikiApp', '0007_auto_20190314_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikimodel',
            name='imageUpload',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
