# Generated by Django 2.2 on 2019-03-18 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikiApp', '0008_auto_20190314_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemmodel',
            name='imageUpload2',
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='imageUpload',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
