# Generated by Django 2.2 on 2019-03-18 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wikiApp', '0009_auto_20190318_0204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemmodel',
            name='imageUpload',
        ),
    ]
